export const weapons = [
  "Wood Sword",
  "Copper Sword",
  "Iron Sword",
  "Nunchucks",
  "Gold Sword",
  "Katana",
  "Frost Sword",
  "Ivy Sword" ,
  "Demonic Sword",
  "Tungsten Sword",
  "Spider Claw",
  "Reinforced Katana",
  "Amethyst Sword",
  "Sand Knife",
  "Cutlass",
  "Bark Blade",
  "Venom Slasher",
  "Aged Champion Sword",
  "Antique Sword",
  "Caustic Executioner",
  "Gemstone Longsword",
  "Iron Greatsword",
  "Frost Greatsword",
  "Ivy Greatsword",
  "Quartz Greatsword",
  "Glacial Greatsword",
  "Slime Greatsword",
  "Ravenwing Greatsword",
  "Necrotic Greatsword",
  "Wood Spear",
  "Copper Spear",
  "Copper Pitchfork",
  "Iron Spear",
  "Gold Spear",
  "Frost Spear",
  "Demonic Spear",
  "Ivy Spear",
  "Void Spear",
  "Tungsten Spear",
  "Vultures Talon",
  "Cryo Spear",
  "Ravenbeak Spear",
  "Gold Glaive",
  "Frost Glaive",
  "Quartz Glaive",
  "Slime Glaive",
  "Cryo Glaive",
  "Wood Boomerang",
  "Tungsten Boomerang",
  "Spider Boomerang",
  "Frost Boomerang",
  "Rolling Pin",
  "Void Boomerang",
  "Razor Blade",
  "Night Razor",
  "Glacial Boomerang",
  "Butcher's Cleaver",
  "Dragons Rebound",
  "Heavy Hammer",
  "Boxing Glove Gun",
  "Lightning Hammer",
  "Carapace Dagger",
  "Galvanic Hammer",
  "Dryad Greathammer",
  "Brute's Battleaxe",
  "Reaper Scythe",
  "Blood Claw",
  "Anchor & Chain",
  "Chef's Special",
  "Void Claw" 
  ] as const;

export const trinkets = [
"Demon Claw",
"Leather Dashers",
"Zephyr Charm",
"Leather Glove",
"Dream Catcher",
"Tracker Boot",
"Regen Pendant",
"Prophecy Slab",
"Forbidden Spellbook",
"Wood Shield",
"Nightmare Talisman",
"Clay Gauntlet",
"Fuzzy Dice",
"Magic Manual",
"Spare Gemstones",
"Chain Shirt",
"Scrying Cards",
"Vambrace",
"Shine Belt",
"Fins",
"Noble Horseshoe",
"Vampires Gift",
"Bone Hilt",
"Magic Foci",
"Manica",
"Explorer Satchel",
"Will-o'-Wisp Lantern",
"Range Foci",
"Zephyr Boots",
"Mesmer Tablet",
"Item Attractor",
"Construction Hammer",
"Tungsten Shield",
"Life Pendant",
"Force of Wind",
"Companion Locket",
"Melee Foci",
"Essence of Rebirth",
"Telescopic Ladder",
"Polar Claw",
"Essence of Prolonging",
"Summon Foci",
"Frenzy Orb",
"Lucky Cape",
"Tool Extender",
"Essence of Perspective",
"Mobility Cloak",
"Hardened Shield",
"Mining Charm",
"Gelatin Casings",
"Bloodstone Ring",
"Frozen Heart",
"Wind Boots",
"Ancient Feather",
"Frozen Wave",
"Inducing Amulet",
"Air Vessel",
"Spell Stone",
"Calming Rose",
"Cactus Shield",
"Traveler Cloak",
"Lifeline",
"Aged Champion Scabbard",
"Spiked Boots",
"Ninjas Mark",
"Challenger's Pauldron",
"Frost Stone",
"Fire Stone",
"Spider Charm",
"Hysteria Tablet",
"Hover Boots",
"Assassins Cowl",
"Second Wind Charm",
"Summoner's Bestiary",
"Guardian Bracelet",
"Spirit Greaves",
"Spirit Board",
"Spiked Bat Boots",
"Miners Prosthetic",
"Guardian Shell",
"Ghost Boots",
"Magical Quiver",
"Siphon Shield",
"Calming Miners Bouquet",
"Parry Buckler",
"Carapace Shield",
"Pirate Telescope",
"Toolbox",
"Digging Claw",
"Frost Flame",
"Shell of Retribution",
"Frozen Soul",
"Balanced Foci",
"Aged Champion Shield",
"Necrotic Soul Skull",
"Scrying Mirror",
"Crystal Shield",
"Explorer Cloak",
"Ammo Box",
"Temple Pendant",
"Ancient Relics",
"Clockwork Heart",
"Blink Scepter",
"Fool's Gambit",
"Balanced Frostfire Foci",
"Kinetic Boots"
] as const;

export const armorSets = [
  "Copper Armor Set",
"Iron Armor Set",
"Leather Armor Set",
"Cloth Armor Set",
"Demonic Armor Set",
"Spider Armor Set",
"Gold Armor Set",
"Runic Armor Set",
"Bloodplate Armor Set",
"Witch Armor Set",
"Soldier Armor Set",
"Frost Armor Set",
"Arachnid Armor Set",
"Ivy Armor Set",
"Quartz Armor Set",
"Gunslinger Armor Set",
"Void Armor Set",
"Thief Armor Set",
"Pharaoh Armor Set",
"Shadow Armor Set",
"Ancient Fossil Armor Set",
"Mycelium Armor Set",
"Glacial Armor Set",
"Tungsten Armor Set",
"Sharpshooter Armor Set",
"Widow Armor Set",
"Ninja Armor Set",
"Nightsteel Armor Set",
"Dawn Armor Set",
"Dusk Armor Set",
"Ravenlords Armor Set",
"Soulseed Armor Set",
"Spiderite Armor Set",
"Dryad Armor Set",
"Slime Armor Set",
"Cryo Witch Armor Set",
"Sapphire Armor Set",
"Arcanic Armor Set",
"Emerald Armor Set",
"Ruby Armor Set",
"Amethyst Armor Set",
] as const;

export type Weapon = typeof weapons[number];
export type Trinket = typeof trinkets[number];
export type ArmorSet = typeof armorSets[number];

export interface Build {
  id: string;
  weapon: Weapon;
  trinket: Trinket;
  armor: ArmorSet;
  createdAt: string;
}
