export const weapons = [
  "Wood Sword",
  "Copper Sword",
  "Iron Sword",
  "Nunchucks",
  "Gold Sword",
  "Katana",
  "Frost Sword",
  "Ivy Sword",
  "Demonic Sword",
  "Tungsten Sword",
  "Spider Claw",
  "Reinforced Katana",
  "Amethyst Sword",
  "Sand Knife",
  "Cutlass",
  "Bark Blade",
  "Venom Slasher",
  "Aged Champion Sword",
  "Antique Sword",
  "Caustic Executioner",
  "Gemstone Longsword",
  "Iron Greatsword",
  "Frost Greatsword",
  "Ivy Greatsword",
  "Quartz Greatsword",
  "Glacial Greatsword",
  "Slime Greatsword",
  "Ravenwing Greatsword",
  "Necrotic Greatsword",
  "Wood Spear",
  "Copper Spear",
  "Copper Pitchfork",
  "Iron Spear",
  "Gold Spear",
  "Frost Spear",
  "Demonic Spear",
  "Ivy Spear",
  "Void Spear",
  "Tungsten Spear",
  "Vultures Talon",
  "Cryo Spear",
  "Ravenbeak Spear",
  "Gold Glaive",
  "Frost Glaive",
  "Quartz Glaive",
  "Slime Glaive",
  "Cryo Glaive",
  "Wood Boomerang",
  "Tungsten Boomerang",
  "Spider Boomerang",
  "Frost Boomerang",
  "Rolling Pin",
  "Void Boomerang",
  "Razor Blade",
  "Night Razor",
  "Glacial Boomerang",
  "Butcher's Cleaver",
  "Dragons Rebound",
  "Heavy Hammer",
  "Boxing Glove Gun",
  "Lightning Hammer",
  "Carapace Dagger",
  "Galvanic Hammer",
  "Dryad Greathammer",
  "Brute's Battleaxe",
  "Reaper Scythe",
  "Blood Claw",
  "Anchor & Chain",
  "Chef's Special",
  "Void Claw",
  "Wood Bow",
  "Copper Bow",
  "Iron Bow",
  "Gold Bow",
  "Frost Bow",
  "Demonic Bow",
  "Ivy Bow",
  "Tungsten Bow",
  "Glacial Bow",
  "Vultures Burst",
  "Dryad Bow",
  "Captor's Shortbow",
  "The Crimson Sky",
  "The Raven's Nest",
  "Necrotic Bow",
  "Bow of Dualism",
  "Antique Bow",
  "Arachnid Web Bow",
  "Ascended Bow",
  "Gold Greatbow",
  "Void Greatbow",
  "Ivy Greatbow",
  "Tungsten Greatbow",
  "Mycelium Greatbow",
  "Night Piercer",
  "Slime Greatbow",
  "Druids Greatbow",
  "Handgun",
  "Webbed Gun",
  "Sapphire Revolver",
  "Machine Gun",
  "Snow Launcher",
  "Shotgun",
  "Sniper Rifle",
  "Flintlock",
  "Hand Cannon",
  "Death Ripper",
  "Cryo Blaster",
  "Living Shotty",
  "Antique Rifle",
  "Shard Cannon",
  "Wood Staff",
  "Sparkler",
  "Sprinkler",
  "Venom Staff",
  "Sapphire Staff",
  "Frost Staff",
  "Quartz Staff",
  "Void Staff",
  "Icicle Staff",
  "Amethyst Staff",
  "Dryad Barrage",
  "Topaz Staff",
  "Emerald Wand",
  "Ruby Staff",
  "Boulder Staff",
  "Void Missile",
  "Slime Staff",
  "Phantom Popper",
  "Emerald Staff",
  "Runebound Scepter",
  "Dredging Staff",
  "Ancient Dredging Staff",
  "Elderly Wand",
  "Shadow Beam",
  "Cryo Quake",
  "The Soulstorm",
  "Venom Shower",
  "Swamp Dweller Staff",
  "Web Weaver",
  "Refractor",
  "Ascended Staff",
  "Spider Staff",
  "Frost Piercer",
  "Magic Branch",
  "Sentient Sword",
  "Dryad Branch",
  "Cryo Staff",
  "Ruby Shields",
  "Orb of Slimes",
  "Brain on a Stick",
  "Stabby Bush",
  "Slime Canister",
  "Phantom Caller",
  "Vulture Staff",
  "Bashy Bush",
  "Reapers Call",
  "Empress Command",
  "Skeleton Staff",
  "Swamps Grasp",
  "Crystallized Skull",
  "Eye of the Void",
  "Blood Bolt",
  "Shadow Bolt",
  "Blood Volley",
  "Swamp Tome",
  "Blood Grimoire",
  "Genie Lamp",
  "Necrotic Flask",
  "Dragon Lance"
] as const;

export const trinkets = [
  "Demon Claw",
  "Leather Dashers",
  "Zephyr Charm",
  "Leather Glove",
  "Dream Catcher",
  "Tracker Boot",
  "Regen Pendant",
  "Prophecy Slab",
  "Forbidden Spellbook",
  "Wood Shield",
  "Nightmare Talisman",
  "Clay Gauntlet",
  "Fuzzy Dice",
  "Magic Manual",
  "Spare Gemstones",
  "Chain Shirt",
  "Scrying Cards",
  "Vambrace",
  "Shine Belt",
  "Fins",
  "Noble Horseshoe",
  "Vampires Gift",
  "Bone Hilt",
  "Magic Foci",
  "Manica",
  "Explorer Satchel",
  "Will-o'-Wisp Lantern",
  "Range Foci",
  "Zephyr Boots",
  "Mesmer Tablet",
  "Item Attractor",
  "Construction Hammer",
  "Tungsten Shield",
  "Life Pendant",
  "Force of Wind",
  "Companion Locket",
  "Melee Foci",
  "Essence of Rebirth",
  "Telescopic Ladder",
  "Polar Claw",
  "Essence of Prolonging",
  "Summon Foci",
  "Frenzy Orb",
  "Lucky Cape",
  "Tool Extender",
  "Essence of Perspective",
  "Mobility Cloak",
  "Hardened Shield",
  "Mining Charm",
  "Gelatin Casings",
  "Bloodstone Ring",
  "Frozen Heart",
  "Wind Boots",
  "Ancient Feather",
  "Frozen Wave",
  "Inducing Amulet",
  "Air Vessel",
  "Spell Stone",
  "Calming Rose",
  "Cactus Shield",
  "Traveler Cloak",
  "Lifeline",
  "Aged Champion Scabbard",
  "Spiked Boots",
  "Ninjas Mark",
  "Challenger's Pauldron",
  "Frost Stone",
  "Fire Stone",
  "Spider Charm",
  "Hysteria Tablet",
  "Hover Boots",
  "Assassins Cowl",
  "Second Wind Charm",
  "Summoner's Bestiary",
  "Guardian Bracelet",
  "Spirit Greaves",
  "Spirit Board",
  "Spiked Bat Boots",
  "Miners Prosthetic",
  "Guardian Shell",
  "Ghost Boots",
  "Magical Quiver",
  "Siphon Shield",
  "Calming Miners Bouquet",
  "Parry Buckler",
  "Carapace Shield",
  "Pirate Telescope",
  "Toolbox",
  "Digging Claw",
  "Frost Flame",
  "Shell of Retribution",
  "Frozen Soul",
  "Balanced Foci",
  "Aged Champion Shield",
  "Necrotic Soul Skull",
  "Scrying Mirror",
  "Crystal Shield",
  "Explorer Cloak",
  "Ammo Box",
  "Temple Pendant",
  "Ancient Relics",
  "Clockwork Heart",
  "Blink Scepter",
  "Fool's Gambit",
  "Balanced Frostfire Foci",
  "Kinetic Boots"
] as const;

export const armorSets = [
  "Copper Armor Set",
  "Iron Armor Set",
  "Leather Armor Set",
  "Cloth Armor Set",
  "Demonic Armor Set",
  "Spider Armor Set",
  "Gold Armor Set",
  "Runic Armor Set",
  "Bloodplate Armor Set",
  "Witch Armor Set",
  "Soldier Armor Set",
  "Frost Armor Set",
  "Arachnid Armor Set",
  "Ivy Armor Set",
  "Quartz Armor Set",
  "Gunslinger Armor Set",
  "Void Armor Set",
  "Thief Armor Set",
  "Pharaoh Armor Set",
  "Shadow Armor Set",
  "Ancient Fossil Armor Set",
  "Mycelium Armor Set",
  "Glacial Armor Set",
  "Tungsten Armor Set",
  "Sharpshooter Armor Set",
  "Widow Armor Set",
  "Ninja Armor Set",
  "Nightsteel Armor Set",
  "Dawn Armor Set",
  "Dusk Armor Set",
  "Ravenlords Armor Set",
  "Soulseed Armor Set",
  "Spiderite Armor Set",
  "Dryad Armor Set",
  "Slime Armor Set",
  "Cryo Witch Armor Set",
  "Sapphire Armor Set",
  "Arcanic Armor Set",
  "Emerald Armor Set",
  "Ruby Armor Set",
  "Amethyst Armor Set",
] as const;

export type Weapon = typeof weapons[number];
export type Trinket = typeof trinkets[number];
export type ArmorSet = typeof armorSets[number];

// Image mappings
export const weaponImages: Record<Weapon, string> = {
  "Wood Sword": "/images/weapons/Wood_Sword.png",
  "Copper Sword": "/images/weapons/Copper_Sword.png",
  "Iron Sword": "/images/weapons/Iron_Sword.png",
  "Nunchucks": "/images/weapons/Nunchucks.png",
  "Gold Sword": "/images/weapons/Gold_Sword.png",
  "Katana": "/images/weapons/Katana.png",
  "Frost Sword": "/images/weapons/Frost_Sword.png",
  "Ivy Sword": "/images/weapons/Ivy_Sword.png",
  "Demonic Sword": "/images/weapons/Demonic_Sword.png",
  "Tungsten Sword": "/images/weapons/Tungsten_Sword.png",
  "Spider Claw": "/images/weapons/Spider_Claw.png",
  "Reinforced Katana": "/images/weapons/Reinforced_Katana.png",
  "Amethyst Sword": "/images/weapons/Amethyst_Sword.png",
  "Sand Knife": "/images/weapons/Sand_Knife.png",
  "Cutlass": "/images/weapons/Cutlass.png",
  "Bark Blade": "/images/weapons/Bark_Blade.png",
  "Venom Slasher": "/images/weapons/Venom_Slasher.png",
  "Aged Champion Sword": "/images/weapons/Aged_Champion_Sword.png",
  "Antique Sword": "/images/weapons/Antique_Sword.png",
  "Caustic Executioner": "/images/weapons/Caustic_Executioner.png",
  "Gemstone Longsword": "/images/weapons/Gemstone_Longsword.png",
  "Iron Greatsword": "/images/weapons/Iron_Greatsword.png",
  "Frost Greatsword": "/images/weapons/Frost_Greatsword.png",
  "Ivy Greatsword": "/images/weapons/Ivy_Greatsword.png",
  "Quartz Greatsword": "/images/weapons/Quartz_Greatsword.png",
  "Glacial Greatsword": "/images/weapons/Glacial_Greatsword.png",
  "Slime Greatsword": "/images/weapons/Slime_Greatsword.png",
  "Ravenwing Greatsword": "/images/weapons/Ravenwing_Greatsword.png",
  "Necrotic Greatsword": "/images/weapons/Necrotic_Greatsword.png",
  "Wood Spear": "/images/weapons/Wood_Spear.png",
  "Copper Spear": "/images/weapons/Copper_Spear.png",
  "Copper Pitchfork": "/images/weapons/Copper_Pitchfork.png",
  "Iron Spear": "/images/weapons/Iron_Spear.png",
  "Gold Spear": "/images/weapons/Gold_Spear.png",
  "Frost Spear": "/images/weapons/Frost_Spear.png",
  "Demonic Spear": "/images/weapons/Demonic_Spear.png",
  "Ivy Spear": "/images/weapons/Ivy_Spear.png",
  "Void Spear": "/images/weapons/Void_Spear.png",
  "Tungsten Spear": "/images/weapons/Tungsten_Spear.png",
  "Vultures Talon": "/images/weapons/Vultures_Talon.png",
  "Cryo Spear": "/images/weapons/Cryo_Spear.png",
  "Ravenbeak Spear": "/images/weapons/Ravenbeak_Spear.png",
  "Gold Glaive": "/images/weapons/Gold_Glaive.png",
  "Frost Glaive": "/images/weapons/Frost_Glaive.png",
  "Quartz Glaive": "/images/weapons/Quartz_Glaive.png",
  "Slime Glaive": "/images/weapons/Slime_Glaive.png",
  "Cryo Glaive": "/images/weapons/Cryo_Glaive.png",
  "Wood Boomerang": "/images/weapons/Wood_Boomerang.png",
  "Tungsten Boomerang": "/images/weapons/Tungsten_Boomerang.png",
  "Spider Boomerang": "/images/weapons/Spider_Boomerang.png",
  "Frost Boomerang": "/images/weapons/Frost_Boomerang.png",
  "Rolling Pin": "/images/weapons/Rolling_Pin.png",
  "Void Boomerang": "/images/weapons/Void_Boomerang.png",
  "Razor Blade": "/images/weapons/Razor_Blade.png",
  "Night Razor": "/images/weapons/Night_Razor.png",
  "Glacial Boomerang": "/images/weapons/Glacial_Boomerang.png",
  "Butcher's Cleaver": "/images/weapons/Butchers_Cleaver.png",
  "Dragons Rebound": "/images/weapons/Dragons_Rebound.png",
  "Heavy Hammer": "/images/weapons/Heavy_Hammer.png",
  "Boxing Glove Gun": "/images/weapons/Boxing_Glove_Gun.png",
  "Lightning Hammer": "/images/weapons/Lightning_Hammer.png",
  "Carapace Dagger": "/images/weapons/Carapace_Dagger.png",
  "Galvanic Hammer": "/images/weapons/Galvanic_Hammer.png",
  "Dryad Greathammer": "/images/weapons/Dryad_Greathammer.png",
  "Brute's Battleaxe": "/images/weapons/Brutes_Battleaxe.png",
  "Reaper Scythe": "/images/weapons/Reaper_Scythe.png",
  "Blood Claw": "/images/weapons/Blood_Claw.png",
  "Anchor & Chain": "/images/weapons/Anchor_Chain.png",
  "Chef's Special": "/images/weapons/Chefs_Special.png",
  "Void Claw": "/images/weapons/Void_Claw.png"
};

export const trinketImages: Record<Trinket, string> = {
  "Demon Claw": "/images/trinkets/Demon_Claw.png",
  "Leather Dashers": "/images/trinkets/Leather_Dashers.png",
  "Zephyr Charm": "/images/trinkets/Zephyr_Charm.png",
  "Leather Glove": "/images/trinkets/Leather_Glove.png",
  "Dream Catcher": "/images/trinkets/Dream_Catcher.png",
  "Tracker Boot": "/images/trinkets/Tracker_Boot.png",
  "Regen Pendant": "/images/trinkets/Regen_Pendant.png",
  "Prophecy Slab": "/images/trinkets/Prophecy_Slab.png",
  "Forbidden Spellbook": "/images/trinkets/Forbidden_Spellbook.png",
  "Wood Shield": "/images/trinkets/Wood_Shield.png",
  "Nightmare Talisman": "/images/trinkets/Nightmare_Talisman.png",
  "Clay Gauntlet": "/images/trinkets/Clay_Gauntlet.png",
  "Fuzzy Dice": "/images/trinkets/Fuzzy_Dice.png",
  "Magic Manual": "/images/trinkets/Magic_Manual.png",
  "Spare Gemstones": "/images/trinkets/Spare_Gemstones.png",
  "Chain Shirt": "/images/trinkets/Chain_Shirt.png",
  "Scrying Cards": "/images/trinkets/Scrying_Cards.png",
  "Vambrace": "/images/trinkets/Vambrace.png",
  "Shine Belt": "/images/trinkets/Shine_Belt.png",
  "Fins": "/images/trinkets/Fins.png",
  "Noble Horseshoe": "/images/trinkets/Noble_Horseshoe.png",
  "Vampires Gift": "/images/trinkets/Vampires_Gift.png",
  "Bone Hilt": "/images/trinkets/Bone_Hilt.png",
  "Magic Foci": "/images/trinkets/Magic_Foci.png",
  "Manica": "/images/trinkets/Manica.png",
  "Explorer Satchel": "/images/trinkets/Explorer_Satchel.png",
  "Will-o'-Wisp Lantern": "/images/trinkets/Will-o-Wisp_Lantern.png",
  "Range Foci": "/images/trinkets/Range_Foci.png",
  "Zephyr Boots": "/images/trinkets/Zephyr_Boots.png",
  "Mesmer Tablet": "/images/trinkets/Mesmer_Tablet.png",
  "Item Attractor": "/images/trinkets/Item_Attractor.png",
  "Construction Hammer": "/images/trinkets/Construction_Hammer.png",
  "Tungsten Shield": "/images/trinkets/Tungsten_Shield.png",
  "Life Pendant": "/images/trinkets/Life_Pendant.png",
  "Force of Wind": "/images/trinkets/Force_of_Wind.png",
  "Companion Locket": "/images/trinkets/Companion_Locket.png",
  "Melee Foci": "/images/trinkets/Melee_Foci.png",
  "Essence of Rebirth": "/images/trinkets/Essence_of_Rebirth.png",
  "Telescopic Ladder": "/images/trinkets/Telescopic_Ladder.png",
  "Polar Claw": "/images/trinkets/Polar_Claw.png",
  "Essence of Prolonging": "/images/trinkets/Essence_of_Prolonging.png",
  "Summon Foci": "/images/trinkets/Summon_Foci.png",
  "Frenzy Orb": "/images/trinkets/Frenzy_Orb.png",
  "Lucky Cape": "/images/trinkets/Lucky_Cape.png",
  "Tool Extender": "/images/trinkets/Tool_Extender.png",
  "Essence of Perspective": "/images/trinkets/Essence_of_Perspective.png",
  "Mobility Cloak": "/images/trinkets/Mobility_Cloak.png",
  "Hardened Shield": "/images/trinkets/Hardened_Shield.png",
  "Mining Charm": "/images/trinkets/Mining_Charm.png",
  "Gelatin Casings": "/images/trinkets/Gelatin_Casings.png",
  "Bloodstone Ring": "/images/trinkets/Bloodstone_Ring.png",
  "Frozen Heart": "/images/trinkets/Frozen_Heart.png",
  "Wind Boots": "/images/trinkets/Wind_Boots.png",
  "Ancient Feather": "/images/trinkets/Ancient_Feather.png",
  "Frozen Wave": "/images/trinkets/Frozen_Wave.png",
  "Inducing Amulet": "/images/trinkets/Inducing_Amulet.png",
  "Air Vessel": "/images/trinkets/Air_Vessel.png",
  "Spell Stone": "/images/trinkets/Spell_Stone.png",
  "Calming Rose": "/images/trinkets/Calming_Rose.png",
  "Cactus Shield": "/images/trinkets/Cactus_Shield.png",
  "Traveler Cloak": "/images/trinkets/Traveler_Cloak.png",
  "Lifeline": "/images/trinkets/Lifeline.png",
  "Aged Champion Scabbard": "/images/trinkets/Aged_Champion_Scabbard.png",
  "Spiked Boots": "/images/trinkets/Spiked_Boots.png",
  "Ninjas Mark": "/images/trinkets/Ninjas_Mark.png",
  "Challenger's Pauldron": "/images/trinkets/Challengers_Pauldron.png",
  "Frost Stone": "/images/trinkets/Frost_Stone.png",
  "Fire Stone": "/images/trinkets/Fire_Stone.png",
  "Spider Charm": "/images/trinkets/Spider_Charm.png",
  "Hysteria Tablet": "/images/trinkets/Hysteria_Tablet.png",
  "Hover Boots": "/images/trinkets/Hover_Boots.png",
  "Assassins Cowl": "/images/trinkets/Assassins_Cowl.png",
  "Second Wind Charm": "/images/trinkets/Second_Wind_Charm.png",
  "Summoner's Bestiary": "/images/trinkets/Summoners_Bestiary.png",
  "Guardian Bracelet": "/images/trinkets/Guardian_Bracelet.png",
  "Spirit Greaves": "/images/trinkets/Spirit_Greaves.png",
  "Spirit Board": "/images/trinkets/Spirit_Board.png",
  "Spiked Bat Boots": "/images/trinkets/Spiked_Bat_Boots.png",
  "Miners Prosthetic": "/images/trinkets/Miners_Prosthetic.png",
  "Guardian Shell": "/images/trinkets/Guardian_Shell.png",
  "Ghost Boots": "/images/trinkets/Ghost_Boots.png",
  "Magical Quiver": "/images/trinkets/Magical_Quiver.png",
  "Siphon Shield": "/images/trinkets/Siphon_Shield.png",
  "Calming Miners Bouquet": "/images/trinkets/Calming_Miners_Bouquet.png",
  "Parry Buckler": "/images/trinkets/Parry_Buckler.png",
  "Carapace Shield": "/images/trinkets/Carapace_Shield.png",
  "Pirate Telescope": "/images/trinkets/Pirate_Telescope.png",
  "Toolbox": "/images/trinkets/Toolbox.png",
  "Digging Claw": "/images/trinkets/Digging_Claw.png",
  "Frost Flame": "/images/trinkets/Frost_Flame.png",
  "Shell of Retribution": "/images/trinkets/Shell_of_Retribution.png",
  "Frozen Soul": "/images/trinkets/Frozen_Soul.png",
  "Balanced Foci": "/images/trinkets/Balanced_Foci.png",
  "Aged Champion Shield": "/images/trinkets/Aged_Champion_Shield.png",
  "Necrotic Soul Skull": "/images/trinkets/Necrotic_Soul_Skull.png",
  "Scrying Mirror": "/images/trinkets/Scrying_Mirror.png",
  "Crystal Shield": "/images/trinkets/Crystal_Shield.png",
  "Explorer Cloak": "/images/trinkets/Explorer_Cloak.png",
  "Ammo Box": "/images/trinkets/Ammo_Box.png",
  "Temple Pendant": "/images/trinkets/Temple_Pendant.png",
  "Ancient Relics": "/images/trinkets/Ancient_Relics.png",
  "Clockwork Heart": "/images/trinkets/Clockwork_Heart.png",
  "Blink Scepter": "/images/trinkets/Blink_Scepter.png",
  "Fool's Gambit": "/images/trinkets/Fools_Gambit.png",
  "Balanced Frostfire Foci": "/images/trinkets/Balanced_Frostfire_Foci.png",
  "Kinetic Boots": "/images/trinkets/Kinetic_Boots.png",
  "Wood Bow": "/images/weapons/Wood_Bow.png",
  "Copper Bow": "/images/weapons/Copper_Bow.png",
  "Iron Bow": "/images/weapons/Iron_Bow.png",
  "Gold Bow": "/images/weapons/Gold_Bow.png",
  "Frost Bow": "/images/weapons/Frost_Bow.png",
  "Demonic Bow": "/images/weapons/Demonic_Bow.png",
  "Ivy Bow": "/images/weapons/Ivy_Bow.png",
  "Tungsten Bow": "/images/weapons/Tungsten_Bow.png",
  "Glacial Bow": "/images/weapons/Glacial_Bow.png",
  "Vultures Burst": "/images/weapons/Vultures_Burst.png",
  "Dryad Bow": "/images/weapons/Dryad_Bow.png",
  "Captor's Shortbow": "/images/weapons/Captors_Shortbow.png",
  "The Crimson Sky": "/images/weapons/The_Crimson_Sky.png",
  "The Raven's Nest": "/images/weapons/The_Ravens_Nest.png",
  "Necrotic Bow": "/images/weapons/Necrotic_Bow.png",
  "Bow of Dualism": "/images/weapons/Bow_of_Dualism.png",
  "Antique Bow": "/images/weapons/Antique_Bow.png",
  "Arachnid Web Bow": "/images/weapons/Arachnid_Web_Bow.png",
  "Ascended Bow": "/images/weapons/Ascended_Bow.png",
  "Gold Greatbow": "/images/weapons/Gold_Greatbow.png",
  "Void Greatbow": "/images/weapons/Void_Greatbow.png",
  "Ivy Greatbow": "/images/weapons/Ivy_Greatbow.png",
  "Tungsten Greatbow": "/images/weapons/Tungsten_Greatbow.png",
  "Mycelium Greatbow": "/images/weapons/Mycelium_Greatbow.png",
  "Night Piercer": "/images/weapons/Night_Piercer.png",
  "Slime Greatbow": "/images/weapons/Slime_Greatbow.png",
  "Druids Greatbow": "/images/weapons/Druids_Greatbow.png",
  "Handgun": "/images/weapons/Handgun.png",
  "Webbed Gun": "/images/weapons/Webbed_Gun.png",
  "Sapphire Revolver": "/images/weapons/Sapphire_Revolver.png",
  "Machine Gun": "/images/weapons/Machine_Gun.png",
  "Snow Launcher": "/images/weapons/Snow_Launcher.png",
  "Shotgun": "/images/weapons/Shotgun.png",
  "Sniper Rifle": "/images/weapons/Sniper_Rifle.png",
  "Flintlock": "/images/weapons/Flintlock.png",
  "Hand Cannon": "/images/weapons/Hand_Cannon.png",
  "Death Ripper": "/images/weapons/Death_Ripper.png",
  "Cryo Blaster": "/images/weapons/Cryo_Blaster.png",
  "Living Shotty": "/images/weapons/Living_Shotty.png",
  "Antique Rifle": "/images/weapons/Antique_Rifle.png",
  "Shard Cannon": "/images/weapons/Shard_Cannon.png",
  "Wood Staff": "/images/weapons/Wood_Staff.png",
  "Sparkler": "/images/weapons/Sparkler.png",
  "Sprinkler": "/images/weapons/Sprinkler.png",
  "Venom Staff": "/images/weapons/Venom_Staff.png",
  "Sapphire Staff": "/images/weapons/Sapphire_Staff.png",
  "Frost Staff": "/images/weapons/Frost_Staff.png",
  "Quartz Staff": "/images/weapons/Quartz_Staff.png",
  "Void Staff": "/images/weapons/Void_Staff.png",
  "Icicle Staff": "/images/weapons/Icicle_Staff.png",
  "Amethyst Staff": "/images/weapons/Amethyst_Staff.png",
  "Dryad Barrage": "/images/weapons/Dryad_Barrage.png",
  "Topaz Staff": "/images/weapons/Topaz_Staff.png",
  "Emerald Wand": "/images/weapons/Emerald_Wand.png",
  "Ruby Staff": "/images/weapons/Ruby_Staff.png",
  "Boulder Staff": "/images/weapons/Boulder_Staff.png",
  "Void Missile": "/images/weapons/Void_Missile.png",
  "Slime Staff": "/images/weapons/Slime_Staff.png",
  "Phantom Popper": "/images/weapons/Phantom_Popper.png",
  "Emerald Staff": "/images/weapons/Emerald_Staff.png",
  "Runebound Scepter": "/images/weapons/Runebound_Scepter.png",
  "Dredging Staff": "/images/weapons/Dredging_Staff.png",
  "Ancient Dredging Staff": "/images/weapons/Ancient_Dredging_Staff.png",
  "Elderly Wand": "/images/weapons/Elderly_Wand.png",
  "Shadow Beam": "/images/weapons/Shadow_Beam.png",
  "Cryo Quake": "/images/weapons/Cryo_Quake.png",
  "The Soulstorm": "/images/weapons/The_Soulstorm.png",
  "Venom Shower": "/images/weapons/Venom_Shower.png",
  "Swamp Dweller Staff": "/images/weapons/Swamp_Dweller_Staff.png",
  "Web Weaver": "/images/weapons/Web_Weaver.png",
  "Refractor": "/images/weapons/Refractor.png",
  "Ascended Staff": "/images/weapons/Ascended_Staff.png",
  "Spider Staff": "/images/weapons/Spider_Staff.png",
  "Frost Piercer": "/images/weapons/Frost_Piercer.png",
  "Magic Branch": "/images/weapons/Magic_Branch.png",
  "Sentient Sword": "/images/weapons/Sentient_Sword.png",
  "Dryad Branch": "/images/weapons/Dryad_Branch.png",
  "Cryo Staff": "/images/weapons/Cryo_Staff.png",
  "Ruby Shields": "/images/weapons/Ruby_Shields.png",
  "Orb of Slimes": "/images/weapons/Orb_of_Slimes.png",
  "Brain on a Stick": "/images/weapons/Brain_on_a_Stick.png",
  "Stabby Bush": "/images/weapons/Stabby_Bush.png",
  "Slime Canister": "/images/weapons/Slime_Canister.png",
  "Phantom Caller": "/images/weapons/Phantom_Caller.png",
  "Vulture Staff": "/images/weapons/Vulture_Staff.png",
  "Bashy Bush": "/images/weapons/Bashy_Bush.png",
  "Reapers Call": "/images/weapons/Reapers_Call.png",
  "Empress Command": "/images/weapons/Empress_Command.png",
  "Skeleton Staff": "/images/weapons/Skeleton_Staff.png",
  "Swamps Grasp": "/images/weapons/Swamps_Grasp.png",
  "Crystallized Skull": "/images/weapons/Crystallized_Skull.png",
  "Eye of the Void": "/images/weapons/Eye_of_the_Void.png",
  "Blood Bolt": "/images/weapons/Blood_Bolt.png",
  "Shadow Bolt": "/images/weapons/Shadow_Bolt.png",
  "Blood Volley": "/images/weapons/Blood_Volley.png",
  "Swamp Tome": "/images/weapons/Swamp_Tome.png",
  "Blood Grimoire": "/images/weapons/Blood_Grimoire.png",
  "Genie Lamp": "/images/weapons/Genie_Lamp.png",
  "Necrotic Flask": "/images/weapons/Necrotic_Flask.png",
  "Dragon Lance": "/images/weapons/Dragon_Lance.png"
};

export const armorImages: Record<ArmorSet, string> = {
  "Copper Armor Set": "/images/armor/Copper_Armor_Set.png",
  "Iron Armor Set": "/images/armor/Iron_Armor_Set.png",
  "Leather Armor Set": "/images/armor/Leather_Armor_Set.png",
  "Cloth Armor Set": "/images/armor/Cloth_Armor_Set.png",
  "Demonic Armor Set": "/images/armor/Demonic_Armor_Set.png",
  "Spider Armor Set": "/images/armor/Spider_Armor_Set.png",
  "Gold Armor Set": "/images/armor/Gold_Armor_Set.png",
  "Runic Armor Set": "/images/armor/Runic_Armor_Set.png",
  "Bloodplate Armor Set": "/images/armor/Bloodplate_Armor_Set.png",
  "Witch Armor Set": "/images/armor/Witch_Armor_Set.png",
  "Soldier Armor Set": "/images/armor/Soldier_Armor_Set.png",
  "Frost Armor Set": "/images/armor/Frost_Armor_Set.png",
  "Arachnid Armor Set": "/images/armor/Arachnid_Armor_Set.png",
  "Ivy Armor Set": "/images/armor/Ivy_Armor_Set.png",
  "Quartz Armor Set": "/images/armor/Quartz_Armor_Set.png",
  "Gunslinger Armor Set": "/images/armor/Gunslinger_Armor_Set.png",
  "Void Armor Set": "/images/armor/Void_Armor_Set.png",
  "Thief Armor Set": "/images/armor/Thief_Armor_Set.png",
  "Pharaoh Armor Set": "/images/armor/Pharaoh_Armor_Set.png",
  "Shadow Armor Set": "/images/armor/Shadow_Armor_Set.png",
  "Ancient Fossil Armor Set": "/images/armor/Ancient_Fossil_Armor_Set.png",
  "Mycelium Armor Set": "/images/armor/Mycelium_Armor_Set.png",
  "Glacial Armor Set": "/images/armor/Glacial_Armor_Set.png",
  "Tungsten Armor Set": "/images/armor/Tungsten_Armor_Set.png",
  "Sharpshooter Armor Set": "/images/armor/Sharpshooter_Armor_Set.png",
  "Widow Armor Set": "/images/armor/Widow_Armor_Set.png",
  "Ninja Armor Set": "/images/armor/Ninja_Armor_Set.png",
  "Nightsteel Armor Set": "/images/armor/Nightsteel_Armor_Set.png",
  "Dawn Armor Set": "/images/armor/Dawn_Armor_Set.png",
  "Dusk Armor Set": "/images/armor/Dusk_Armor_Set.png",
  "Ravenlords Armor Set": "/images/armor/Ravenlords_Armor_Set.png",
  "Soulseed Armor Set": "/images/armor/Soulseed_Armor_Set.png",
  "Spiderite Armor Set": "/images/armor/Spiderite_Armor_Set.png",
  "Dryad Armor Set": "/images/armor/Dryad_Armor_Set.png",
  "Slime Armor Set": "/images/armor/Slime_Armor_Set.png",
  "Cryo Witch Armor Set": "/images/armor/Cryo_Witch_Armor_Set.png",
  "Sapphire Armor Set": "/images/armor/Sapphire_Armor_Set.png",
  "Arcanic Armor Set": "/images/armor/Arcanic_Armor_Set.png",
  "Emerald Armor Set": "/images/armor/Emerald_Armor_Set.png",
  "Ruby Armor Set": "/images/armor/Ruby_Armor_Set.png",
  "Amethyst Armor Set": "/images/armor/Amethyst_Armor_Set.png"
};

export interface Build {
  id: string;
  weapon: Weapon;
  trinket: Trinket[];
  armor: ArmorSet;
  createdAt: string;
}